name: CI/CD — .NET 8 + Docker + VPS

on:
  push:
    branches:
      - master   # adapte si ta branche principale est "main"

env:
  REGISTRY_USER: ${{ secrets.VPS_DOCKER_USERNAME }}
  REGISTRY_PASS: ${{ secrets.VPS_DOCKER_PASSWORD }}
  IMAGE_NAME: dotnet-app

concurrency:
  group: cicd-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-dotnet:
    name: Build & Restore (.NET)
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      # Optionnel: Tests
      # - name: Test
      #   run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

      - name: Compute version
        id: version
        run: |
          echo "version=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

  docker-publish:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    needs: build-dotnet
    outputs:
      image_tag: ${{ steps.meta.outputs.sha }}
      image_ref: ${{ steps.tags.outputs.image_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch, optionnel)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASS }}

      - name: Derive tags
        id: tags
        run: |
          SHA=${{ needs.build-dotnet.outputs.version }}
          echo "image_ref=${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}" >> "$GITHUB_OUTPUT"
          echo "sha=${SHA}" >> "$GITHUB_OUTPUT"

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # ajoute d'autres plateformes si nécessaire: linux/arm64
          platforms: linux/amd64
          tags: |
            ${{ steps.tags.outputs.image_ref }}:latest
            ${{ steps.tags.outputs.image_ref }}:${{ steps.tags.outputs.sha }}
          cache-from: type=registry,ref=${{ steps.tags.outputs.image_ref }}:buildcache
          cache-to: type=registry,ref=${{ steps.tags.outputs.image_ref }}:buildcache,mode=max

  deploy-vps:
    name: Deploy on VPS (SSH)
    runs-on: ubuntu-latest
    needs: docker-publish
    environment:
      name: production
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            cd ${{ secrets.VPS_APP_DIR }}

            # .env pour docker-compose (aligné avec ta stack)
            install -m 600 /dev/null .env
            cat > .env << 'EOF'
            APP_IMAGE=${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:latest
            DB_HOST=sqlserver
            DB_PORT=1433
            DB_NAME=CesiZEN
            DB_USER=sa
            SQL_SA_PASSWORD=${{ secrets.SQL_SA_PASSWORD }}
            CONNECTION_STRING=Server=${DB_HOST},${DB_PORT};Database=${DB_NAME};User Id=${DB_USER};Password=${SQL_SA_PASSWORD};Encrypt=True;TrustServerCertificate=True
            EOF

            # Réseau externe commun à l'app et au conteneur SQL existant
            sudo docker network inspect cesi >/dev/null 2>&1 || sudo docker network create cesi

            # Si un conteneur "sqlserver" existe déjà, le raccorder au réseau
            if sudo docker ps -a --format '{{.Names}}' | grep -qx 'sqlserver'; then
              sudo docker network connect cesi sqlserver 2>/dev/null || true
            else
              echo "Attention: aucun conteneur nommé 'sqlserver' trouvé. Vérifie le nom du conteneur DB."
            fi

            # Mettre à jour et redémarrer uniquement le service "app"
            sudo docker compose pull app
            sudo docker compose up -d app
            sudo docker image prune -f
