name: Publish to Docker Hub

on:
  push:
    branches:
      - master   # change si ta branche principale n'est pas "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup .NET 8
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3️⃣ Restaurer dépendances
      - name: Restore dependencies
        run: dotnet restore

      # 4️⃣ Build projet (Release)
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # 5️⃣ Tests (optionnel)
     # - name: Run tests
      #  run: dotnet test --no-build --verbosity normal

      # 6️⃣ Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.VPS_DOCKER_USERNAME }}
          password: ${{ secrets.VPS_DOCKER_PASSWORD }}

      # 7️⃣ Build et push image Docker
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.VPS_DOCKER_USERNAME }}/dotnet-app:latest
