name: Publish to Docker Hub

on:
  push:
    branches:
      - master   # change si ta branche principale n'est pas "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup .NET 8 SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3️⃣ Restaurer dépendances
      - name: Restore dependencies
        run: dotnet restore

      # 4️⃣ Build projet (Release)
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # 5️⃣ Lancer les migrations EF Core
      - name: Run EF migrations
        run: dotnet ef database update \
              --project DotNetIdentity/DotNetIdentity.csproj \
              --connection "${{ secrets.DB_CONNECTION }}"

      # 6️⃣ Login Docker Hub (seulement si migrations OK ✅)
      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.VPS_DOCKER_USERNAME }}
          password: ${{ secrets.VPS_DOCKER_PASSWORD }}

      # 7️⃣ Build et push image Docker (seulement si migrations OK ✅)
      - name: Build and Push Docker image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.VPS_DOCKER_USERNAME }}/dotnet-app:latest

      # 8️⃣ Deploy via SSH sur VPS (seulement si image pushée ✅)
      - name: Deploy on VPS
        if: success()
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.VPS_DOCKER_USERNAME }}/dotnet-app:latest
            sudo docker stop dotnet-app || true
            sudo docker rm dotnet-app || true
            sudo docker run -d --name dotnet-app -p 80:80 ${{ secrets.VPS_DOCKER_USERNAME }}/dotnet-app:latest
